package com.gti350.labo1;

import com.gti350.labo1.listeners.SwipeGestureListener;
import com.gti350.labo1.listeners.SwipeGestureListener.IOnSwipeListener;
import com.gti350.labo1.models.Fighter;

import android.content.Intent;
import android.os.Bundle;
import android.support.v4.view.GestureDetectorCompat;
import android.text.Editable;
import android.util.Log;
import android.view.MotionEvent;
import android.widget.EditText;
import android.widget.Scroller;

/**
 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
 * @version 1.0
 */
public class FighterDefinitionActivity extends BaseActivity {

	/** The logging tag to quickly identify logs generated by this class. */
	private static final String LoggingTag = FighterDefinitionActivity.class.getName();

	/** */
	private GestureDetectorCompat gestureDetector;

	private Scroller scroller;

	/** */
	private EditText redFighterTextbox;

	/** */
	private EditText blueFighterTextbox;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_fighter_definition);

		// Cache useful controls.
		redFighterTextbox = (EditText) findViewById(R.id.textbox_red_fighter);
		blueFighterTextbox = (EditText) findViewById(R.id.textbox_blue_fighter);

		// Create the listener for swiping.
		SwipeGestureListener swipeGestureListener = new SwipeGestureListener(new OnPreviousSwipeListener(), new OnNextSwipeListener());
		gestureDetector = new GestureDetectorCompat(this, swipeGestureListener);
		scroller = new Scroller(FighterDefinitionActivity.this);

		// Get the extras from the intent.
		Bundle extras = getIntent().getExtras();
		if (extras == null) {
			return;
		}

		// Check if fighters object are already serialized.
		// If so, use their state to repopulate this activity.
		Fighter redFighter = (Fighter) extras.get(BaseActivity.RedFighterKey);
		if (redFighter != null) {
			redFighterTextbox.setText(redFighter.getName());
		}

		Fighter blueFighter = (Fighter) extras.get(BaseActivity.BlueFighterKey);
		if (blueFighter != null) {
			blueFighterTextbox.setText(blueFighter.getName());
		}
	}

	@Override
	public boolean onTouchEvent(MotionEvent event) {
		// Check if the swipe detector can handle the event.
		// Else, pass the event along to the super class.
		return gestureDetector.onTouchEvent(event) || super.onTouchEvent(event);
	}

	/**
	 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
	 * @version 1.0
	 */
	private class OnPreviousSwipeListener implements IOnSwipeListener {
		@Override
		public boolean onSwipe(MotionEvent event1, MotionEvent event2, float velocityX, float velocityY) {
			Intent i = new Intent(FighterDefinitionActivity.this, MainActivity.class);

			finish();
			startActivity(i);
			return true;
		}
	}

	/**
	 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
	 * @version 1.0
	 */
	private class OnNextSwipeListener implements IOnSwipeListener {
		@Override
		public boolean onSwipe(MotionEvent event1, MotionEvent event2, float velocityX, float velocityY) {
			// Validate current activity content.
			Editable redFighterName = redFighterTextbox.getText();
			Editable blueFighterName = blueFighterTextbox.getText();
			boolean redFighterValid = !redFighterName.toString().isEmpty();
			boolean blueFighterValid = !blueFighterName.toString().isEmpty();

			if (redFighterValid && blueFighterValid) {
				// Valid.
				Log.i(LoggingTag, "Fighter definitions were valid.");

				Intent i = new Intent(FighterDefinitionActivity.this, JudgeDefinitionActivity.class);
				Fighter redFighter = new Fighter(Fighter.FighterColor.Red, redFighterName.toString());
				Fighter blueFighter = new Fighter(Fighter.FighterColor.Blue, blueFighterName.toString());

				i.putExtra(BaseActivity.RedFighterKey, redFighter);
				Log.i(LoggingTag, "Serialized red fighter.");

				i.putExtra(BaseActivity.BlueFighterKey, blueFighter);
				Log.i(LoggingTag, "Serialized blue fighter.");

				finish();
				startActivity(i);
				return true;
			} else {
				// Invalid.
				Log.i(LoggingTag, "Detected invalid fighter definition.");

				if (!redFighterValid) {
					redFighterTextbox.setError(getString(R.string.red_fighter_empty));
				}

				if (!blueFighterValid) {
					blueFighterTextbox.setError(getString(R.string.blue_fighter_empty));
				}

				return false;
			}
		}
	}
}
