package com.gti350.labo1;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;

/**
 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
 * @version 1.0
 */
public class MainActivity extends BaseActivity {

	/** The logging tag to quickly identify logs generated by this class. */
	private static final String LoggingTag = MainActivity.class.getName();

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		// Bind touch events on buttons.
		Button settingsButton = (Button) findViewById(R.id.button_settings);
		settingsButton.setOnClickListener(new OnSettingsButtonClicked());

		Button startFightButton = (Button) findViewById(R.id.button_start_fight);
		startFightButton.setOnClickListener(new OnStartFightButtonClicked());
	}

	/**
	 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
	 * @version 1.0
	 */
	private class OnSettingsButtonClicked implements View.OnClickListener {
		@Override
		public void onClick(View v) {
			displayAlert("Unimplemented", "Not implemented.");
		}
	}

	/**
	 * @author Laurianne Michaud, Alexandre Billot, Simon Turcotte-Langevin
	 * @version 1.0
	 */
	private class OnStartFightButtonClicked implements View.OnClickListener {
		@Override
		public void onClick(View v) {
			// Start the fighter's definition activity.
			Intent i = new Intent(MainActivity.this, FighterDefinitionActivity.class);

			startActivity(i);
			finish();
		}
	}
}
